name: Deployment
on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Lint
        run: |
          yarn
          yarn build
          yarn lint
      - name: Version Bump
        id: versionbump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default: patch
          minor-wording: add,Adds,new
          major-wording: MAJOR,cut-major
          patch-wording: patch,fixes
          rc-wording: RELEASE,alpha
      - name: Sync Version
        run: yarn syncv
     - name: Create Release
       id: createrelease
       uses: actions/create-release@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         tag_name: ${{ steps.versionbump.newTag }}
         release_name: Release ${{ steps.versionbump.newTag }}
         draft: false
         prerelease: false

  build_ubuntu:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          # https://tauri.studio/docs/getting-started/setting-up-linux#1-system-dependencies
          sudo apt update && sudo apt install libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libappindicator3-dev \
            librsvg2-dev
          yarn
          yarn tauri build
      - name: Upload Release Assets
        uses: NBTX/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ jobs.prepare.outputs.createrelease.outputs.upload_url }}
          targets: src-tauri/target/release/bundle/*/*

  build_windows:
    runs-on: windows-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          yarn
          yarn tauri build
          Move-Item -Path .\src-tauri\target\release\pauspapier.exe -Destination .\src-tauri\target\release\bundle\msi\
      - name: Upload Release Assets
        uses: NBTX/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ jobs.prepare.outputs.createrelease.outputs.upload_url }}
          targets: src-tauri/target/release/bundle/msi/*

  build_macos:
    runs-on: macos-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          yarn
          yarn tauri build
      - name: Upload Release Assets
        uses: NBTX/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ jobs.prepare.outputs.createrelease.outputs.upload_url }}
          targets: src-tauri/target/release/bundle/*/*
